### ISSUE TITLE
`static_alias` renders only if you have a block named "content"

### ISSUE THREAD

**Issue by aacimov** [django-cms/djangocms-alias#212]
I am not sure if this should be a feature request but I usually have a block named _base_content_ instead of _content_ since I sometimes have a different _base.html_ file for different purposes.

`static_alias` can be edited only if a block named _content_ exists in the template. I suppose it's by design and by best practices but just a thought.

I was struggling for a few minutes why I cannot edit my `static_alias` so maybe it will be helpful to others.

Or just adding a note to the docs as an indicator it is actually a dependency in the template.

Python 3.10.6
Django 4.2.9
Django CMS 4.1.0
djangocms-alias 2.0.0

**Comment by fsbraun** [comment]
Hi @aacimov ! 

The default setup of django CMS Alias assumes you have a block called "content" in your `base.html`.  You can, however, change that:

In your project, create a template called `djangocms_alias/base.html` with the following content:

```
{% extends "base.html" %}
{% load i18n static sekizai_tags %}

{% block title %}{% trans "Aliases" %}{% endblock %}

{% block breadcrumb %}{% endblock %}
{% block footer %}{% endblock %}

{% block base_content %}
    <div class="aliases">
        {% block aliases_content %}
        {% endblock aliases_content %}
    </div>
{% endblock base_content %}
```

Make sure that the new template is loaded instead of the default one (e.g. by looking at the order of apps in `INSTALLED_APPS`).

**Comment by aacimov** [comment]
Hi @fsbraun,

Thanks for the quick answer and a suggestion. That would be somewhat of overriding any of the default plugin templates, am I correct?

Just consider adding a note that `{% block content %}` should be used for the default, _out of the box_ behaviour to the documentation. There could be people naming the main content block in their own names.

It's just a suggestion from my end.

Thanks a lot.

**Comment by fsbraun** [comment]
@aacimov Can I encourage you to add this information to the readme file?

**Comment by aacimov** [comment]
> @aacimov Can I encourage you to add this information to the readme file?

Of course. No problem. Just point me to the process on how to do it properly.
