### ISSUE TITLE
wizard related error

### ISSUE THREAD

**Issue by joshyu** [django-cms/djangocms-alias#244]
As @fsbraun removed the `get_absolute_url` via this PR ( https://github.com/django-cms/djangocms-alias/pull/199), and our `new alias` entry is in the wizard creation. so we will get some errors when we create new alias and alias category via wizard button.

![image](https://github.com/user-attachments/assets/17ba31b0-2b6e-4ca8-a30f-3d2ed63b81c3)

This is related to below function call in `wizard_base.py` fil in django cms
<img width="444" alt="image" src="https://github.com/user-attachments/assets/810cde47-6dc2-4f44-b398-033830dec848">

I think we need to fix that.

@fsbraun , 
please provide your input.

**Comment by fsbraun** [comment]
@joshyu Well spotted! Indeed, the default wizard assumes the model created has a `get_absolute_url` method, `AliasCategory` does not since it does not offer a URL to the user space.

We need to overwrite `get_success_url` in the alias category wizard. It needs to return the category's `get_admin_change_url`. Would you like to make a PR?

**Comment by joshyu** [comment]
@fsbraun, 
How to override the `get_success_url` in the alias? Do you have any reference for me?
sorry I didn't work on this part before. I need a sample, you can tell me to check which addon.

**Comment by fsbraun** [comment]
Just add a method to this: https://github.com/django-cms/djangocms-alias/blob/3dfa143dad6189cdbca19a3133b7419fac56d2a8/djangocms_alias/cms_wizards.py#L17-L21

Something like:
```
def get_success_url(self, obj, **kwargs):
    return obj.get_admin_change_url()
```

**Comment by joshyu** [comment]
@fsbraun ,

please help to review the PR #245
